

let navList = [
  {
    name:'概览',
    path:'/console',
    icon:'gailan',
    label:'',
    sub:[
      {
        name:'概览',
        path:'/console',
        icon:'gailan',
      }
    ]
  },
  {
    label:'计算',
    sub:[
      {
        name:'弹性云主机',
        path:'/ecm/ecmList',
        icon:'vm',
      },
      {
        name:'镜像',
        path:'/ecm/ims/imsList',
        icon:'iso'
      },
      {
        name:'快照',
        path:'/ecm/snapshot/snapshotList',
        icon:'iso',
      },
      {
        name:'SSH秘钥对',
        path:'/ecm/keypair/keypairList',
        icon:'technology-nav',
        type:'os',
        hide:true
      }
    ]
  },
  {
    label:'存储',
    sub:[
      {
        name:'云硬盘',
        path:'/ecm/ebs/ebsList',
        icon:'ebs-nav',
      }
    ]
  },
  {
    label:'网络',
    sub:[
      {
        name:'虚拟私有云',
        path:'/vpc/vpcList',
        icon:'vpc-nav',
      },
      {
        name:'子网',
        path:'/vpc/net/netList',
        icon:'subnet-nav',
      },
      {
        name:'弹性公网IP',
        path:'/vpc/eip/eipList',
        icon:'publicIp-nav',
      },
      {
        name:'ACL',
        path:'/vpc/acl/aclList',
        icon:'acl-nav',
        type:'cs',
        hide:true
      },
      {
        name:'安全组',
        path:'/vpc/sec/secList',
        icon:'acl-nav',
        type:'os',
        hide:true
      },
      {
        name:'负载均衡',
        path:'/elb/elbList',
        icon:'lb-nav',
        type:'cs',
        hide:true
      },
    ]
  },
  {
    label:'云监控',
    sub:[
      {
        name:'Dashboard',
        path:'/monitor/dashboard',
        icon:'dashboard',
      },
      {
        name:'云服务器监控',
        path:'/monitor/ecmMonitor',
        icon:'monitor-nav',
      },
      {
        name:'云硬盘监控',
        path:'/monitor/ebsMonitor',
        icon:'monitor-nav',
      },
    ]
  },
  {
    label:'应用服务',
    sub:[
      {
        name:'技术服务',
        path:'',
        icon:'technology-nav',
      },
      {
        name:'域名服务',
        path:'',
        icon:'domain-nav',
      },
    ]
  }

]


export default navList;
